version: '3.1'

services:
  authorizer:
    container_name: "authorizer"
    build: "./authorizer"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    env_file:
      - .env
    networks:
      - microservices

  candidate:
    container_name: "candidate"
    build: "./candidate"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${CANDIDATE_PORT}:${CANDIDATE_PORT}
    env_file:
      - .env
    networks:
      - microservices

  evaluator:
    container_name: "evaluator"
    build: "./evaluator"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${EVALUATOR_PORT}:${EVALUATOR_PORT}
    env_file:
      - .env
    networks:
      - microservices

  company:
    container_name: "company"
    build: "./company"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${COMPANY_PORT}:${COMPANY_PORT}
    env_file:
      - .env
    networks:
      - microservices

  project:
    container_name: "project"
    build: "./project"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${PROJECT_PORT}:${PROJECT_PORT}
    env_file:
      - .env
    networks:
      - microservices

  postgres:
    container_name: "postgres"
    image: postgres:15.4-alpine3.18
    restart: always
    env_file:
      - .env
    networks:
      - microservices
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 2s
      timeout: 30s
      retries: 5

  api:
    container_name: "api"
    build: "./api"
    networks:
      - microservices
    ports:
      - ${API_SECURE_PORT}:${API_PORT}
    env_file:
      - .env
    depends_on:
      - authorizer
      - candidate
      - evaluator
      - company
      - project
      - postgres

networks:
  microservices:
    driver: bridge
