import LanguageSelector from '@/components/LanguageSelector'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang='en' className='h-full bg-white'>
      <body className={`h-full ${inter.className}`}>
        {children}
        <footer className='fixed bottom-0 p-3 bg-gray-100 w-full text-sm'>
          You're in <span className='text-gray-500'>Colombia</span>, do you want
          to change the language? <LanguageSelector />
        </footer>
      </body>
    </html>
  )
}
