name: CD Pipeline

on:
  workflow_run:
    workflows: [ "Run Tests and Generate Docker Images" ]
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull DockerImage from Dockerhub
        run: sudo docker pull acantu297366/authorizer:latest
      - name: Delete old docker container
        run: sudo docker rm -f authorizer-container || true
      - name: Run docker container
        run: sudo docker run -p 8080:8080 --name authorizer-container acantu297366/authorizer
