name: CI-Tests-CD-Integration

on:
  push:
    branches:
      - 'HU/**'
  pull_request:
    types:
      - opened
    branches:
      - 'HU/**'
      - 'develop'

jobs:
  continuos-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Access to AWS Instance
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}
          AWS_HOST_IP: ${{secrets.AWS_HOST_IP}}
          AWS_USERNAME: ${{secrets.AWS_USERNAME}}
        script: echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > key.pem | chmod 400 key.pem | ssh -i key.pem ${{secrets.AWS_USERNAME}}@${{secrets.AWS_HOST_IP}}
      - name: Run docker compose in aws
        script: sudo docker compose up &