name: Run Tests

on:
  push:
    branches:
      - 'HU/**'
  pull_request:
    types:
      - opened
    branches:
      - 'HU/**'
      - 'develop'

jobs:
  prepare-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: 18.x

  authorizer-tests:
    runs-on: ubuntu-latest
    needs: prepare-env
    steps:
      - name: Print Working Directory
        run: pwd
      - name: List files
        run: ls -la
      - name: Navigate to authorizer
        run: cd authorizer
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test

  web-tests:
    runs-on: ubuntu-latest
    needs: prepare-env
    steps:
      - name: Enable corepack
        run: corepack enable
      - name: Navigate to web
        run: cd web
      - name: Install dependencies
        run: pnpm i
      - name: Run tests
        run: pnpm test
