name: CI-Tests-CD-Integration

on:
  push:
    branches:
      - 'HU/**'
  pull_request:
    types:
      - opened
    branches:
      - 'HU/**'
      - 'develop'

jobs:
  continuos-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Access to AWS Instance
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{ secrets.PASSPHRASE }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          script: |
            echo "${{ secrets.PASSPHRASE }}" > tr -d '\r' > key.pem  
            chmod 400 key.pem
            ssh -i key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.PORT }}
            sudo docker compose up &
