name: Run Tests

on:
  push:
    branches:
      - 'HU/**'
  pull_request:
    branches:
      - 'HU/**'
      - 'develop'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/checkout@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test


