name: Run Tests

on:
  push:
    branches:
      - 'HU/**'
  pull_request:
    types:
      - opened
    branches:
      - 'HU/**'
      - 'develop'

jobs:
  authorizer-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: 18.x
      - name: Install dependencies
        working-directory: authorizer
        run: npm i
      - name: Run tests
        working-directory: authorizer
        run: npm run test

  web-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: 18.x
      - name: Enable corepack
        working-directory: web
        run: corepack enable
      - name: Install dependencies
        working-directory: web
        run: pnpm i
      - name: Run tests
        working-directory: web
        run: pnpm test
